data:
  AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU7
  AzureWebJobsSecretStorageType: ZmlsZXM=
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  CosmosDBConnectionString: bW9uZ29kYjovL25laWdoYm9ybHlhcHBjb3Ntb3NkYjpzM1FDdDFsQ3ZRTE5VU1R6UGFmWlNZMUs5R3FtMEFOZnhDTktZTklKOG5XMzJnZjJUOWtvMnFDQ0x2MGpadDE3ZUlyNjFpVUlFdXVaak44STB3QU9odyUzRCUzREBuZWlnaGJvcmx5YXBwY29zbW9zZGIubW9uZ28uY29zbW9zLmF6dXJlLmNvbToxMDI1NS8/c3NsPXRydWUmcmVwbGljYVNldD1nbG9iYWxkYiZyZXRyeXdyaXRlcz1mYWxzZSZtYXhJZGxlVGltZU1TPTEyMDAwMCZhcHBOYW1lPUBuZWlnaGJvcmx5YXBwY29zbW9zZGJA
apiVersion: v1
kind: Secret
metadata:
  name: neighborlyappcluster
---
data:
  host.master: akowd0FReVA5Z3BIeWlNbEZOSUxvNWRTbXFNY0xZUTdBNDlrMjJHZ1RCQ1dsVUZKb0EyZnhnPT0=
  host.function.default: NDRKNHZuUUVjNXNvdmVMNjZXT3Y2Z3Mzc2xkUzd4UnpGQVFpL3BaZnZyU0N3UVpuTTA5SktnPT0=
  host.systemKey.default: bTlRYWhFWE9ySkF4MU1XNWlXMmViTWhhL0h6NzhOeTZlbmFQQjNCNUpRTEdtcFFsWWdoZElnPT0=
  functions.createadvertisement.default: RGl1ZC9BVkwvVEhZekFHWHM2RjBhMHQvdjRsdzZzQmxUSW00azZiNFBYZ2Z2UXMwQWFhVU9BPT0=
  functions.deleteadvertisement.default: YWt3NkYwZUIwTi8yVjNEUUlzMjV2dzhVeENycEFRSFdWSmE5MkJPcVhvTHQydWhrYmRwWXRnPT0=
  functions.getadvertisement.default: ZFo4ZS9PdnR0Y05WL1ozWmZiMm00RU1selVCMEhoaGQ5aG1GZDhUUGR2N1Q2MlNtcUFNVTl3PT0=
  functions.getadvertisements.default: Z1E5S2ttbWVxbklZSnI2Q0p0WmFvQk9qR1I4N3J1TUZaMmR6RGlBYWJKTkNzZUd0RS8zMk9BPT0=
  functions.getpost.default: TTQ5bjBVTWhPRFRhNHRLT092eUs1N2FDZ3NYb2hNWkVkUGc1Q2FWQ1dQa2tiZWE1YWxqNGJnPT0=
  functions.getposts.default: NjR4SkRnZnF4Q2d5VXdnYUNzc25xTXVZdGNYckJTZ3dKL1FTcEhqazBKSjlPckFkS094bWlBPT0=
  functions.updateadvertisement.default: OUVGYy9LYXlaMEozS2FCd3BEbWZvbmpzNW9hZ0EyeGprZ0NFQ2RYSDZkWjl4R3VucFhMbHVnPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-neighborlyappcluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neighborlyappcluster-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: neighborlyappcluster-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neighborlyappcluster-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: neighborlyappcluster-http
spec:
  selector:
    app: neighborlyappcluster-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborlyappcluster-http
  labels:
    app: neighborlyappcluster-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neighborlyappcluster-http
  template:
    metadata:
      labels:
        app: neighborlyappcluster-http
    spec:
      containers:
      - name: neighborlyappcluster-http
        image: jerryneighborlyappregistry.azurecr.io/neighborlyappimage:v1
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-neighborlyappcluster
        envFrom:
        - secretRef:
            name: neighborlyappcluster
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborlyappcluster-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborlyappcluster
  labels:
    app: neighborlyappcluster
spec:
  selector:
    matchLabels:
      app: neighborlyappcluster
  template:
    metadata:
      labels:
        app: neighborlyappcluster
    spec:
      containers:
      - name: neighborlyappcluster
        image: jerryneighborlyappregistry.azurecr.io/neighborlyappimage:v1
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: neighborlyappcluster
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborlyappcluster-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: neighborlyappcluster
  labels: {}
spec:
  scaleTargetRef:
    name: neighborlyappcluster
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

